### PR TITLE
Add util module

### LINKED ISSUE #40: Provide useful functions in a Util module
### Problem

As @avsm pointed out in [this discuss post](https://discuss.ocaml.org/t/ocaml-yaml-extracting-value-using-a-key/6396/8), and thanks to @kyp0717 for initiating the discussion, real world Yaml seems to be primarily about encoding the JSON subset rather than the more complex features the Yaml spec can encode i.e. using the `Yaml.value` type.

As such, whilst ocaml-yaml serves those who wish to use complex Yaml files, some simple utility functions for those using the `Yaml.value` type are missing and would be useful for those wishing to use the library. This issue proposes adding a `Yaml.Util` module providing basic combinators for working with the `Yaml.value` type. 

### Examples  

A lot of inspiration can be taken from the excellent `Yojson.Basic.Util` module. Some simple functions that would be good would be: 

```ocaml
val keys : value -> string list res 
(** [keys yml] returns the keys of an object *)

val values : value -> value list res 
(** [values yml] will return a list of all values stored in a list-like value  *)

val member : string -> value -> value res
(** [member key d] returns the value wrapped in [Ok] associated with [key] otherwise [Error _] *) 

val map : (value -> value) -> value -> value res 
(** [map f v] applies [f] to each element of [v] *)

(* "Unboxing" functions *)
val to_string : value -> string res 
val to_float : value -> float res
val to_bool : value -> bool res 
```

These can then be combined using the `Rresult` library that Yaml already uses. For example:

```ocaml
let () =
  let open Rresult in
  let yml = Yaml.of_string "hello: world" in
  yml >>= member "hello" >>= to_string
  |> R.pp ~ok:Format.pp_print_string ~error:R.pp_msg Format.std_formatter
(* Prints "world" *)
```

### PR DESCRIPTION
**Pull request by patricoferris**
This PR adds a `Yaml.Util` module providing some common functions for manipulating `Yaml.value` values or building simple yaml values from OCaml primitives. It mostly follows the naming convention of having `f` and `f_exn` the former using the result type and the latter raising an exception. This fixes #40.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
These functions would be very useful to have. 
Added `crowbar` dependency here https://github.com/avsm/ocaml-yaml/pull/45

**Comment by avsm** [comment]
The functions look good to me, but why put them in a `Util` module?  The functions fit right in the main Yaml module as far as I can tell, as they offer operations over `Yaml.value` .

**Comment by patricoferris** [comment]
I put it in a separate module and included it inside `yaml.ml` just because I thought `yaml.ml` was getting a little crowded, I can copy the functions in `yaml.ml` 👍

**Comment by avsm** [comment]
Let's leave the Util module there, since there's a name clash with the `to_string` functions. Merging with thanks!

**Pull request merged**
