### PR TITLE
Support YAML 1.2

### PR DESCRIPTION
**Pull request by favonia**
It seems we can support YAML 1.2 effortlessly. This PR does the following three things:

1. Update upstream code.
2. Add an optional argument to `document_start` so that `version` can be passed to the C library.
3. Remove the support of YAML 1.0 because the C library does not seem to support YAML 1.0.

### CODE REVIEW

**Comment by favonia** [comment]
Disclaimer: The C library seems to support important YAML 1.2 changes as discussed in https://github.com/yaml/libyaml/issues/20, though the [YAML 1.2 test suite](https://matrix.yaml.io/) indicates it's still missing many edge cases. To me, its support of YAML 1.2 is good enough.

In any case, there are important segfault bugfixes in the upstream and we should update the code.

**Comment by favonia** [comment]
It seems the maintainers are not interested in this PR, and I have no interest in maintaining it indefinitely, either. Feel free to reopen it and pick up what I left.

**Comment by avsm** [comment]
Thanks for the PR!
> In any case, there are important segfault bugfixes in the upstream and we should update the code.
Agreed; it's difficult to assess Yaml 1.2 coverage, but I agree with removing Yaml 1.0 (which seems to never be emitted anyway from the library) and moving the OCaml-exposed sig to 1.1 and 1.2

> It seems the maintainers are not interested in this PR

s/maintainers/maintainer :-) Since you seem to be a user of this, would you like to help co-maintain it? I'd be happy to give you a merge bit.

Otherwise, I'll be merging this soon after root-causing the CI failure on 32-bit (which appears to be an unrelated bug in my investigations so far)

**Comment by favonia** [comment]
Thanks for the invitation. :-) I am currently not working on a project using this library, and will revisit this PR only later.

**Comment by avsm** [comment]
the 32-bit failure was an overflow in an internal buffer (aaa85920ea38def28e361cb2ec5f97147337ab73) and now fixed. This is all merged and will be in yaml 3.0. Thanks for the excellent contribution and patience, @favonia!

**Pull request merged**
