### PR TITLE
Fix cflags logic which produced an empty flag

### LINKED ISSUE #13: Build issue, trying to compile ''
`opam install yaml` fails with:

```
#=== ERROR while compiling yaml.0.2.1 =========================================#
# context     2.0.0 | linux/x86_64 | ocaml-variants.4.07.1+fp+flambda | https://opam.ocaml.org#0f5c409f
# path        ~/.opam/4.07.1+fp+flambda/.opam-switch/build/yaml.0.2.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder build -p yaml -j 3
# exit-code   1
# env-file    ~/.opam/log/yaml-15370-05296d.env
# output-file ~/.opam/log/yaml-15370-05296d.out
### output ###
# gcc: error: : No such file or directory                                                                                            
# [...]
# (cd _build/default/vendor && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -g -fno-omit-frame-pointer -fPIC -O2 -fno-strict-aliasing -fwrapv -g '' -fno-omit-frame-pointer -Wall -DHAVE_CONFIG_H -I. -c parser.c)
# gcc: error: : No such file or directory
#          gcc vendor/reader.o (exit 1)
# (cd _build/default/vendor && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -g -fno-omit-frame-pointer -fPIC -O2 -fno-strict-aliasing -fwrapv -g '' -fno-omit-frame-pointer -Wall -DHAVE_CONFIG_H -I. -c reader.c)
# gcc: error: : No such file or directory
#          gcc vendor/scanner.o (exit 1)
# (cd _build/default/vendor && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -g -fno-omit-frame-pointer -fPIC -O2 -fno-strict-aliasing -fwrapv -g '' -fno-omit-frame-pointer -Wall -DHAVE_CONFIG_H -I. -c scanner.c)
# gcc: error: : No such file or directory
#          gcc vendor/writer.o (exit 1)
# (cd _build/default/vendor && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -g -fno-omit-frame-pointer -fPIC -O2 -fno-strict-aliasing -fwrapv -g '' -fno-omit-frame-pointer -Wall -DHAVE_CONFIG_H -I. -c writer.c)
# gcc: error: : No such file or directory



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build yaml 0.2.1
└─ 
```

I have installed libyaml-dev, didn't help.
Same error trying to build master with dune.

### PR DESCRIPTION
**Pull request by g2p**
Closes #13.

### CODE REVIEW

**Comment by avsm** [comment]
thanks; what version of gcc/os triggered this bug?

**Comment by g2p** [comment]
OS is Ubuntu bionic, with an OCaml 4.07.1 switch.

```
ocamlc -config |grep ocamlopt_cflags
ocamlopt_cflags: -O2 -fno-strict-aliasing -fwrapv -g  -fno-omit-frame-pointer
```

Notice the two spaces after the `-g` flag, which ended up as an empty line in the cflags file, and an empty argument after.

**Comment by emillon** [comment]
ping @avsm, can we merge this? at the moment this is pinned in g2p/wodan, would be great to upstream this patch :)

(a more declarative solution would be to use `String.split_on_char` but this requires ocaml >= 4.04)

Thanks!

**Comment by avsm** [comment]
sorry for blocking on this -- i actually wanted to get this into configurator upstream as it seems brittle for other uses as well. I'm just about to hop on the eurostar to tarides so will work on it today/tomorrow from paris :-)

**Comment by avsm** [comment]
(but if you have a chance to look into this upstream in dune I think that's better, and this whole repo can be switched to use dune.configurator)

**Comment by emillon** [comment]
Oh, I didn't realize this was the old configurator! Will have a look at this.

**Comment by avsm** [comment]
superseded by ´18

**Pull request closed without merging**
